[workspace]
members = [
    "utils",
    "day01",
    "runner",
]

resolver = "2"

[workspace.dependencies]
utils = { path = "utils" }
itertools = "0.13"
regex = "1.10"
rayon = "1.10"
anyhow = "1.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16

[profile.dev]
opt-level = 1
